services:
  db:
   container_name: db
   image: postgres:latest
   ports:
     - 5432:5432
   environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_DB: ${DB_NAME}
   volumes:
     - ./volume/postgres:/var/lib/postgresql/data
   restart: always