"""User add field email

Revision ID: 5ef575ad004b
Revises: 392173ff287c
Create Date: 2025-03-19 02:28:14.483029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ef575ad004b"
down_revision: Union[str, None] = "392173ff287c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user's", sa.Column("email", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user's", "email")
    # ### end Alembic commands ###
